name: gdlint
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    name: "Lint"
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
          
      - name: create-requirements-if-not-exists
        run: |
          if [ ! -f requirements.txt ]; then
            echo "gdtoolkit==3.*" > requirements.txt
          fi
        shell: bash
        
      - name: Setup python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: "3.x"
          cache: "pip"

      - name: Upgrade setuptools
        run: pip install --upgrade setuptools

      - name: Install gdtoolkit
        run: pip install gdtoolkit==3.*
      - name: Setup gdtoolkit
        uses: Scony/godot-gdscript-toolkit@master

      - name: Lint
        run: gdlint scripts/
