name: Update README on New Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Replace version in README
        run: |
          NEW_VERSION=$(echo "${{ github.ref }}" | sed -E 's/^refs\/tags\/v//')
          sed -Ei 's/(v[0-9]+\.[0-9]+\.[0-9]+)/${NEW_VERSION}/g' README.md

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with new version $NEW_VERSION"
          git push
